version: '3.7'

x-default14:
  &default-odoo15
  tty: true
  build:
    context: ./configs/15.0
  volumes:
    - odoo15-web-data:/var/lib/odoo
    - ./configs/15.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/15.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

  &default-odoo14
  tty: true
  build:
    context: ./configs/14.0
  volumes:
    - odoo14-web-data:/var/lib/odoo
    - ./configs/14.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/14.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default13:
  &default-odoo13
  tty: true
  build:
    context: ./configs/13.0
  volumes:
    - odoo13-web-data:/var/lib/odoo
    - ./configs/13.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/13.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

x-default11:
  &default-odoo11
  tty: true
  build:
    context: ./configs/11.0
  volumes:
    - odoo11-web-data:/var/lib/odoo
    - ./configs/11.0/odoo.conf:/etc/odoo/odoo.conf
    - ./vendor/11.0:/mnt/vendor
    - ./.adminpasswd:/run/secrets/adminpasswd

services:
  web11:
    << : *default-odoo11
    depends_on:
      - db
      - longpolling11
    ports:
      - "11069:8069"

  longpolling11:
    << : *default-odoo11
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "11072:8072"

  web13:
    << : *default-odoo13
    depends_on:
      - db
      - longpolling13
    ports:
      - "13069:8069"

  longpolling13:
    << : *default-odoo13
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "13072:8072"

  web14:
    << : *default-odoo14
    depends_on:
      - db
      - longpolling14
    ports:
      - "14069:8069"

  longpolling14:
    << : *default-odoo14
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "14072:8072"

  web15:
    << : *default-odoo15
    depends_on:
      - db
      - longpolling15
    ports:
      - "15069:8069"

  longpolling15:
    << : *default-odoo15
    depends_on:
      - db
    command: ['odoo', 'gevent']
    ports:
      - "15072:8072"
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo11-web-data:
  odoo13-web-data:
  odoo14-web-data:
  odoo15-web-data:
  odoo-db-data:
